// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5PZmyVt_yU2EXNIoiSJWBDpaP8ld_8Fo',
    appId: '1:418002180543:web:794ac9bc7fd1049e1aa90a',
    messagingSenderId: '418002180543',
    projectId: 'flutter-firebasetest-97361',
    authDomain: 'flutter-firebasetest-97361.firebaseapp.com',
    storageBucket: 'flutter-firebasetest-97361.appspot.com',
    measurementId: 'G-T6PWRMYT20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqdeyCSnJi-fUIkMUZKvODOuW9uJXER-w',
    appId: '1:418002180543:android:aad4f17ebc97e1171aa90a',
    messagingSenderId: '418002180543',
    projectId: 'flutter-firebasetest-97361',
    storageBucket: 'flutter-firebasetest-97361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5K8zZg_-feQIPzR7pqXtLww49OHYR9e4',
    appId: '1:418002180543:ios:8d7179e76180b7091aa90a',
    messagingSenderId: '418002180543',
    projectId: 'flutter-firebasetest-97361',
    storageBucket: 'flutter-firebasetest-97361.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5K8zZg_-feQIPzR7pqXtLww49OHYR9e4',
    appId: '1:418002180543:ios:2fdeccf8a369be361aa90a',
    messagingSenderId: '418002180543',
    projectId: 'flutter-firebasetest-97361',
    storageBucket: 'flutter-firebasetest-97361.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
